### PR TITLE
Add logging to SqsWorker

### PR DESCRIPTION
**Pull request by Danielss89**
At the moment it is not possible to get the exception when a job fails.

### CODE REVIEW

**Comment by basz** [comment]
@jackdpeterson ping. what do you think about such an addition? I can see why it's useful to be able to capture exceptions. But this fix is Sql specific, perhaps we should try to make it more generic. The very minimum we should to add a static property to the events class that replaces the 'logException' string...

from Beanstalkd worker
> In Beanstalkd, if an error occurs (exception for instance), the job is automatically reinserted into the queue after a configured delay(the "visibility_timeout" option). If the job executed correctly, it must explicitly be removed.

from SQS worker
> In SQS, if an error occurs (exception for instance), the job is automatically reinserted into the queue after a configured delay (the "visibility_timeout" option). If the job executed correctly, it must explicitly be removed

SlmDoctrine exceptions are 'buried' by the worker and the exceptions is logged with it.

**Comment by Danielss89** [comment]
What do you mean about it being sql specific?
I Will change it to be a static property!
man. 25. jun. 2018 kl. 13.04 skrev Bas Kamer <notifications@github.com>:

**Comment by basz** [comment]
I meant specific to the SlmSQS adapter. (grrrr. autocorrect)

I'm looking fo a more generic solution that all adapters can use. In that case the event name should be added to Event class which is provided by the base Slm package... Therefore i ping'd @jackdpeterson 

I'd wait what he has to say, before changing anything

**Comment by Danielss89** [comment]
Ahh ok haha xD
Great, i Will follow this too!
man. 25. jun. 2018 kl. 13.10 skrev Bas Kamer <notifications@github.com>:

**Comment by Danielss89** [comment]
Any news on this?
@basz  @jackdpeterson

**Pull request closed without merging**
